(define nil '())
(define (double x) (+ x x))
(define (square x) (* x x))
(define (mymap f x)
  (cond ((null? x) nil)
        (else (cons (f (car x)) (mymap f (cdr x))))))
(mymap double '(1 2 3))
;answer (2 4 6)
(mymap square '(1 2 3))
;answer (1 4 9)