(define (myappend x z)
  (cond ((null? x)z)
        (else (cons (car x) (myappend (cdr x) z)))))
(myappend '() '(a b c))
;answer (a b c)
(myappend '(a b c) '(d e))
;answer (a b c d e)
(myappend '(x y z) '(ade bc))
;answer (x y z abe bc)